name: CI/CD Pipeline

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install nbconvert
          pip install notebook

      - name: Install Jupyter Kernel
        run: |
          python -m ipykernel install --user --name python3 --display-name "Python 3"

      - name: List kernels
        run: |
          jupyter kernelspec list

      - name: List files
        run: |
          dir

      - name: Run notebook
        run: |
          jupyter nbconvert --to notebook --execute --ExecutePreprocessor.kernel_name=python3 ./path/to/notebook.ipynb --output executed_notebook.ipynb

      - name: Upload executed notebook
        uses: actions/upload-artifact@v2
        with:
          name: executed-notebook
          path: executed_notebook.ipynb
